version: '3.8'

services:
  api_instance_1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coco-admin-ui-1
    restart: always
    ports:
      - "80:8080"  
    env_file:
      - ./api/.env  # Ensure the correct path to .env
    networks:
      - coco-network

  api_instance_2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coco-admin-ui-2
    restart: always
    ports:
      - "8081:8080"  
    env_file:
      - ./api/.env  
    networks:
      - coco-network

networks:
  coco-network:
    driver: bridge  
